### ISSUE TITLE
Phoenix 1.7 Bandit LiveView demo / reference implementation

### ISSUE THREAD

**Issue by niccolox** [tanguilp/plug_http_cache_demo#1]
ok @tanguilp you have really rocked my world with this innovation 

I've done customer engineering in the edge app space professionally using Varnish and bringing caching into the plug space is really quite amazing

for my hobby project I switched to Phoenix 1.7, moving to Live View and also Bandit

I guess I'll start exploring your libraries by forking this repo and upgrading and see where I end up

right now my stack is 

Bandit
Plug
Phoenix 1.7
Phoenix Live View
Cachex
Nginx local (caching)
Wasabi S3 (image caching)
Cloudflare (default cache, which is weak on fremium plans)

its pretty clumsy really and I would love to be able to simplify and bring the caching closer to the app

thanks for this work

**Comment by niccolox** [comment]
nice write-up btw
https://svground.fr/blog/posts/introducing-http-cache/

I did some experiments with creating cacheable cookieless pipelines
https://github.com/niccolox/phx_html_cookieless

**Comment by niccolox** [comment]
followup question: how does plug_http_cache compare to CacheEx?

**Comment by tanguilp** [comment]
Hi! Thanks for the kind words :)

> I guess I'll start exploring your libraries by forking this repo and upgrading and see where I end up
Keep me informed if you find some problems.

> nice write-up btw
> https://svground.fr/blog/posts/introducing-http-cache/

http://svground.fr/blog/posts/introducing-http-cache/ if you want CSS. Just noticed.

> followup question: how does plug_http_cache compare to CacheEx?
Not comprehensive:
- plug&play. Just set the right `cache-control` header and it should work OOTB
- automatic gzip (de)compression
- support for conditional requests
- support for revalidation & HEAD request (refreshing headers)
- support for range requests
- invalidation by URL and alternate key
- clustering support (sharing responses, warmup & broadcast of invalidation requests)
- fine-tuned telemetry events
- in licensed version: HTTP request coalescing, brotli compression, disk persistence, SSD protection, caching incomplete responses and combining 206 responses (soon)

I've not taken a look at CacheEx for some time, but I think these features are not supported.

**Comment by niccolox** [comment]
I tried to pull in your caching ecosystem into my phx 1.7 app and found numerous issues

1. distillery and edeliver choke on otp25, had to go to forks to make them work
2. your demo is phoenix 1.6 and uses MIx, 1.7 uses Config

I'll try to find time to fork this demo and upgrade and get it working with fly and edeliver/distillery

I do really like the simplicity and matching on routes vs Cachex which caches ecto queries I think basically

**Comment by tanguilp** [comment]
> distillery and edeliver choke on otp25, had to go to forks to make them work

Yeah `http_cache` requires OTP24+, `http_cache_store_memory` requires OTP25+ and `http_cache_store_disk` requires OTP26+. We use new features of OTP.

> your demo is phoenix 1.6 and uses MIx, 1.7 uses Config
> I'll try to find time to fork this demo and upgrade and get it working with fly and edeliver/distillery

PR welcome! Maybe I should include the `.tools-version` file.

One more note: hex's `plug_cache_control` won't work with OTP26+, because of a new keyword added (`dynamic()`). Which is why we use a forked version from my repository in this project.

**Comment by tanguilp** [comment]
I was transferred ownership of `plug_cache_control` and updated it on hex.pm and in `mix.exs` FYI.

**Comment by niccolox** [comment]
> PR welcome! Maybe I should include the .tools-version file.

I would like to see the OTP 26 tool versions for asdf

I am trying this right now

```
elixir 1.16.0-rc.1-otp-26
erlang 26.2
```

**Comment by tanguilp** [comment]
I am using:

```shell
$ asdf current
elixir          1.14.1
erlang          26.0.1
```

and it works just fine.

The `disk-backend` branch requires OTP26+, I've just updated the README.

**Comment by niccolox** [comment]
ok, thanks for the help

I *think* I got the branch and versions above working i.e. caching on a controller index for a landing page

question I have, is, cookies and Phoenix

am I right to think Phoenix always generates a cookie? its simply not possible for Phoenix conn to work without said cookie

I want to generate cached pages that have no cookies that will be cached on edge/CDN like Cloudflare

if you have insights or examples on caching in Phoenix AND CDN (Cloudflare) with or without cookies on controllers or routes I would be most grateful

my previous experience was with Varnish and cookie caching is a no-no and rarely is caching done of cookies, usually cookies are stripped before caching in Varnish, afaik

I see you have caching of authorized responses and I must confess I am interested to learn examples of how that would work in Phoenix

fwiw, some simple tests I am seeing 20-30% improvement in performance on GTmetrix and Webpagetest even without Cloudflare HTML caching (although I am using a more powerful Proxmox VPS in OVH with latest OTP26). Elixir 1.6 broke numerous modules and so I backed off Elixir upgrades

THANKS

**Comment by niccolox** [comment]
I am looking at replacing this plug

```elixir
defmodule FolkbotWeb.Plug.CacheControl do
  @moduledoc """
  Manages the adding of cache-control headers to public requests so CDN
  can do some caching
  """
  import Plug.Conn

  def init(opts), do: opts

  def call(conn = %{assigns: %{current_user: user}}, _opts) when not is_nil(user), do: conn

  # https://developers.cloudflare.com/cache/about/cache-control/
  # Cache assets with revalidation, but allow stale responses if origin server is unreachable
  # https://developer.fastly.com/learning/concepts/cache-freshness/#surrogate-control
  def call(conn, _opts) do
    conn
    |> put_resp_header("cache-control", "max-age=3600, stale-while-revalidate=60, stale-if-error=604800")
    |> put_resp_header(
         "surrogate-control",
         "max-age=3600, stale-while-revalidate=60, stale-if-error=604800"
       )
  end
end
```

with something like this 
```elixir
defmodule FolkbotWeb.Plug.Cache do
  @moduledoc """
  Manages the adding of cache-control headers to public requests so CDN
  can do some caching
  """
  import Plug.Conn

  def init(opts), do: opts

  def call(conn = %{assigns: %{current_user: user}}, _opts) when not is_nil(user), do: conn

  def call(conn, _opts) do
    plug PlugCacheControl, [directives: [:public, s_maxage: 60 * 20], replace: true]
  end
end
```

digging into PlugCacheControl now

**Comment by niccolox** [comment]
I think this works

```elixir
defmodule FolkbotWeb.Plug.Cache do
  @moduledoc """

  """
  import Plug.Conn

  def init(opts), do: opts

  def call(conn = %{assigns: %{current_user: user}}, _opts) when not is_nil(user), do: conn

  def call(conn, _opts) do
    opts = PlugCacheControl.init([directives: [:public, s_maxage: 2 * 20]])
    conn = PlugCacheControl.call(conn, opts)
  end

end
```

**Comment by tanguilp** [comment]
> am I right to think Phoenix always generates a cookie? its simply not possible for Phoenix conn to work without said cookie

Not necessarily. First you have to differentiate setting a cookie (Phoenix side), and the browser sending the set cookie.

Phoenix can work without cookies. However, some plug do set cookies, such as `:protect_from_forgery`, which is automatically installed in the browser pipeline.

In most cases, of course, you should not cache pages that set cookies, because the `set-cookie` header will be cached as well, which is a big security issue. Thus, you need to have:
- private, non-cacheable pages that set cookies
- public pages that do not set cookies

I've been thinking of adding a `PlugHTTPCache.PreventSettingCookies` plug to add in the caching pipeline.

NB: I just noticed that the demo does set cookies on cached pages :sweat: Need to fix it and update documentation.

> I see you have caching of authorized responses and I must confess I am interested to learn examples of how that would work in Phoenix

This one is not about cookies, but the `authorization` header. Imagine you have a paid service for weather forecast up to 300 days, thanks to a super AI you've developed. It's gonna be the same cacheable data for all your clients, therefore you can return the same results to them all for a given page. However, you still need to make them pay, and therefore first verify they've subscribed before sending the result. You would do something like this on your API:

```elixir
plug UserAuthenticated
plug UserHasSubscribed
plug PlugHTTPCache, @opts
```

The first plug deals with the `authorization` header (authenticating the user), the second verifies authorization (the user is allowed to access data because he has subscribed to a plan) and eventually you return the cached version if needed.

> fwiw, some simple tests I am seeing 20-30% improvement in performance on GTmetrix and Webpagetest even without Cloudflare HTML caching (although I am using a more powerful Proxmox VPS in OVH with latest OTP26).

Sounds great, thanks for feedback. Which backend are you using: memory or disk?

> I am looking at replacing this plug

If I may ask, why not using the `PlugCacheControl` directly like in https://github.com/tanguilp/plug_http_cache_demo/blob/master/lib/plug_http_cache_demo_web/router.ex#L16?

**Comment by tanguilp** [comment]
> if you have insights or examples on caching in Phoenix AND CDN (Cloudflare) with or without cookies on controllers or routes I would be most grateful

I don't, unfortunately.

**Comment by tanguilp** [comment]
> Phoenix can work without cookies. However, some plug do set cookies, such as :protect_from_forgery, which is automatically installed in the browser pipeline.

This plug sets the cookie through the [`Plug.Conn.rehister_before_send/2`](https://hexdocs.pm/plug/Plug.Conn.html#register_before_send/2) callback, which is called before `PlugHTTPCache` in the demo. Since the callbacks are called in reverse order, the response is cached before the cookie is set. Sheer luck.

However we need a mechanism to prevent setting cookies. I'm thinking of 3 possibilites:
- A `PlugHTTPCache.PreventSettingCookies` plug
- An option to `plug_http_cache`
- Ahn option to `http_cache`

All have pros & cons, not sure how to proceed here. If you have an opinion, feel free to share!

**Comment by niccolox** [comment]
> > if you have insights or examples on caching in Phoenix AND CDN (Cloudflare) with or without cookies on controllers or routes I would be most grateful
> 
> I don't, unfortunately.

its on my list; 
Cloudflare paid plans have HTML with cookie caching options. 
A second option is to remove cookies entirely, which I think breaks Phoenix pretty much entirely

**Comment by tanguilp** [comment]
> A second option is to remove cookies entirely, which I think breaks Phoenix pretty much entirely

Not at all, actually!

By default, AFAIK, the only plug that set cookies is `:protect_from_forgery`. Remove it and - voilà! - no cookie will be set.

Ideally you want to separate pipelines:

```elixir
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PlugHTTPCacheDemoWeb.LayoutView, :root}
    plug :put_secure_browser_headers
  end

  pipeline :public do
    plug PlugCacheControl, directives: [:public, s_maxage: 60 * 20]
    plug PlugHTTPCache, Application.get_env(:plug_http_cache_demo, :plug_http_cache_opts)
  end

  pipeline :private do
    plug :protect_from_forgery
    plug PlugCacheControl, directives: [:public, s_maxage: 60 * 20]
  end
```

and configure your routes accordingly.

**Comment by niccolox** [comment]
thanks for all of this information and feedback

your plug caching ecosystem is very useful and I am very encouraged by your participation

working in edge CDN space I saw how important to the economics of hosting caching is and its not obvious from the mainline Phoenix docs how its done

Varnish (as you know) is a proxy layer with all sorts of weirdness

its really nice to bake caching into the core app and build out an Elixir cluster to provide horizontal and vertical scaling

**Comment by niccolox** [comment]
DM at https://twitter.com/niccolox 
interested to chat with you about all these projects
cheers

**Comment by niccolox** [comment]
```bash
curl -I https://ark.devekko.com/about
HTTP/2 200 
date: Tue, 19 Dec 2023 06:35:24 GMT
content-type: text/html; charset=utf-8
cache-control: stale-while-revalidate=60, s-maxage=3600, stale-if-error=604800, public
x-request-id: F6InoGNc_itPg54AAADE
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
vary: accept-encoding
age: 6
cf-cache-status: HIT
last-modified: Tue, 19 Dec 2023 06:35:18 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=1clcTxGPNEjOmQfFPostz8V%2FWWKNGK2oUn4jMOTQINJgiZUl4tShseVy1%2B7wPB7%2F3vYZrTGSTQic3WUyk0BR8ENGxSgPd6Bt8GceH%2FkZxaCs0gFRoBnlw6ubQcp9INEo2aPzXKq%2FcYdhfs6xoAc%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 837da0150dbc2560-SJC
alt-svc: h3=":443"; ma=86400
```

2 cloudflare cache rules
cache hostname
cache bypass cookie

bingo 👍🏻

**Comment by tanguilp** [comment]
> your plug caching ecosystem is very useful and I am very encouraged by your participation

And you feedback is more than welcome!

> DM at https://twitter.com/niccolox

I saw you started following me. Feel free to DM first :)

> bingo bongo 👍🏻

Yikes! Although I'm not sure to understand what it means. When curling, I randomly receive hits and misses :thinking: 

I'll update `http_cache` with an option to raise if a cookie is set in a private cache. I think it's the best way to do it. Then I'll update `plug_http_cache` doc with the above pipelines and update this project as well.

**Comment by tanguilp** [comment]
BTW I noticed your title includes LiveView. Right now caching LiveViews with session doesn't work OOTB.

We're working on this though there: https://github.com/phoenixframework/phoenix/pull/5667

**Comment by niccolox** [comment]
> > your plug caching ecosystem is very useful and I am very encouraged by your participation
> 
> And you feedback is more than welcome!
> 
> > DM at https://twitter.com/niccolox
> 
> I saw you started following me. Feel free to DM first :)

maybe I need to be a paid user or something now on Twitter, but I cant DM you, will research this more

> 
> > bingo  👍🏻
> 
> Yikes! Although I'm not sure to understand what it means. >
 
oh god, I just looked that up also. I edited it. Something I heard somewhere, had no idea of the background

> When curling, I randomly receive hits and misses 🤔

I changed the ```max-age``` and it seems to be giving more HITS

> I'll update `http_cache` with an option to raise if a cookie is set in a private cache. I think it's the best way to do it. Then I'll update `plug_http_cache` doc with the above pipelines and update this project as well.

let me know, I will try to the changes

**Comment by niccolox** [comment]
> This one is not about cookies, but the `authorization` header. Imagine you have a paid service for weather forecast up to 300 days, thanks to a super AI you've developed. It's gonna be the same cacheable data for all your clients, therefore you can return the same results to them all for a given page. However, you still need to make them pay, and therefore first verify they've subscribed before sending the result. You would do something like this on your API:
> 
> ```elixir
> plug UserAuthenticated
> plug UserHasSubscribed
> plug PlugHTTPCache, @opts
> ```
> 
> The first plug deals with the `authorization` header (authenticating the user), the second verifies authorization (the user is allowed to access data because he has subscribed to a plan) and eventually you return the cached version if needed.

Does Phoenix use the authorization header? I am not seeing it. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization


> > fwiw, some simple tests I am seeing 20-30% improvement in performance on GTmetrix and Webpagetest even without Cloudflare HTML caching (although I am using a more powerful Proxmox VPS in OVH with latest OTP26).
> 
> Sounds great, thanks for feedback. Which backend are you using: memory or disk?
disk right now on a single server. I am planning on setting up a second and third server and doing memory in a cluster


> 
> > I am looking at replacing this plug
> 
> If I may ask, why not using the `PlugCacheControl` directly like in https://github.com/tanguilp/plug_http_cache_demo/blob/master/lib/plug_http_cache_demo_web/router.ex#L16?

I have a pattern match in a cache control which excludes cache control headers when current_user, perhaps I need to refactor to be more dry about authentication, caching etc

```elixir
defmodule FolkbotWeb.Plug.PlugCacheControl do
  @moduledoc """
  Manages the adding of cache-control headers to public requests so CDN
  can do some caching
  """
  import Plug.Conn

  def init(opts), do: opts

  def call(conn = %{assigns: %{current_user: user}}, _opts) when not is_nil(user), do: conn

  def call(conn, [directives]) do
    # directives = [directives: [:public, s_maxage: 14400, stale_while_revalidate: 60, stale_if_error: 604800]]
    opts = PlugCacheControl.init([directives])
    conn = PlugCacheControl.call(conn, opts)
  end

end
```
controller

```elixir
  alias FolkbotWeb.Plug.PlugCacheControl

#  directives = [directives: [:public, s_maxage: 14400, stale_while_revalidate: 60, stale_if_error: 604800]]
  plug PlugCacheControl, [directives: [:public, s_maxage: 14400, stale_while_revalidate: 60, stale_if_error: 604800]] when action in [:index, :showslug, :show]
  plug :assign_post when action in [:show, :showslug, :sblah, :edit, :update]
  plug Authorize, [FolkbotWeb.Policies.Post, :post]
  plug :scrub_params, "post" when action in [:create, :update]

```

**Comment by tanguilp** [comment]
> let me know, I will try to the changes

I've just discovered that Plug treats cookies in a special way, and it's set after everything else. So there's actually no chance of caching them by mistake.

> Does Phoenix use the authorization header?

The authorization header is more for API access. It is supported via third-party libraries, for instance [APIac](https://github.com/tanguilp/apiac).

> I have a pattern match in a cache control which excludes cache control headers when current_user, perhaps I need to refactor to be more dry about authentication, caching etc

Isn't there a chance that:
- unauthenticated user makes a request to the page
- the page is cached
- authenticated user males a request to the same page
- the cached page, for unauthenticated user, is returned
?

Or many you won't return cached pages for authenticated users?

**Comment by niccolox** [comment]
> Isn't there a chance that:
> 
> * unauthenticated user makes a request to the page
> * the page is cached
> * authenticated user males a request to the same page
> * the cached page, for unauthenticated user, is returned
>   ?
> 
> Or many you won't return cached pages for authenticated users?

good catch

router now
```elixir
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FolkbotWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug FolkbotWeb.Plug.Authenticate, repo: Folkbot.Repo
    plug FolkbotWeb.Plug.PlugCacheControl, [directives: [:public, s_maxage: 960, stale_while_revalidate: 60, stale_if_error: 604800]] 
    plug FolkbotWeb.Plug.FlocOff
    plug FolkbotWeb.Plugs.AssignWebsite, repo: Folkbot.Repo
    plug FolkbotWeb.Plugs.AssignSessionWebsite, repo: Folkbot.Repo
  end
```

plug now, I think this is logical problem you highlighted, I may need to adjust this more

```elixir
defmodule FolkbotWeb.Plug.PlugCacheControl do
  import Plug.Conn

  def init(opts), do: opts

  def call(conn = %{assigns: %{current_user: user}}, _opts) when not is_nil(user), do: conn

  def call(conn = %{assigns: %{current_user: nil}}, [directives]) do
    # directives = [directives: [:public, s_maxage: 14400, stale_while_revalidate: 60, stale_if_error: 604800]]
    opts = PlugCacheControl.init([directives])
    conn = PlugCacheControl.call(conn, opts)
  end

  def call(conn, [directives]) do
    # directives = [directives: [:public, s_maxage: 14400, stale_while_revalidate: 60, stale_if_error: 604800]]
    opts = PlugCacheControl.init([directives])
    conn = PlugCacheControl.call(conn, opts)
  end

end
```

**Comment by niccolox** [comment]
> I've just discovered that Plug treats cookies in a special way, and it's set after everything else. So there's actually no chance of caching them by mistake.

how so? can you expand on that?

> BTW I noticed your title includes LiveView. Right now caching LiveViews with session doesn't work OOTB.
> 
> We're working on this though there: [phoenixframework/phoenix#5667](https://github.com/phoenixframework/phoenix/pull/5667)

DM me on Twitter, or email me at niccolox@devekko.com I have some suggestions

**Comment by niccolox** [comment]
> BTW I noticed your title includes LiveView. Right now caching LiveViews with session doesn't work OOTB.
> 
> We're working on this though there: [phoenixframework/phoenix#5667](https://github.com/phoenixframework/phoenix/pull/5667)



> DM at https://twitter.com/niccolox interested to chat with you about all these projects cheers

I turned on my DMs on Twitter, looks like they are not open by default

regarding LiveView, I think you need to put the session/cookie on the websocket stream and cache the html that is not the DOM patch ws
https://www.facebook.com/notes/10158791368532200/

**Comment by tanguilp** [comment]
> plug now, I think this is logical problem you highlighted, I may need to adjust this more

I still think what you wanna do here is:
- to return cached page for unauthenticated user
- to **not** return cached page for authenticated users

This is doable, but keep in mind that you should **not** return cache control headers beyond your Phoenix app if you do so, because intermediary proxies (CloudFlare...) will cache the page for everybody, unless you configure something there as well.

Usually, you have public, cacheable pages and private, non-cacheable ones. Please expand on your use-case because it's not clear to me and if I guessed correctly what you try to achieve, then the problem with returning cached pages to authenticated users may remain.

Long story short you shouldn't set cache control headers that allow caching on private pages that shouldn't be cached by shared caches. If you do so you gonna have problems ☺

> regarding LiveView, I think you need to put the session/cookie on the websocket stream and cache the html that is not the DOM patch ws
Caching private liveviews is actually what I'm trying to achieve. Some PRs remain to be merged in Phoenix & Phoenix LiveView, it's still a long way. But it would be the best of both world.

> how so? can you expand on that?
Yes, and gonna have to write about this:
- when using the session `Plug.Conn.put_session/3`, the `set-cookie` header is not directly set
- instead, session data is kept in memory
- the `set-cookie` header is set [just before](https://github.com/elixir-plug/plug/blob/b05cd27012511426d1c75834fe66566539ee89cd/lib/plug/conn.ex#L1848-L1867) the response is sent to the adapter (cowboy for instance)
- as a consequence, one has no way of accessing the `set-cookie` header even through the[ registered callbacks ](https://hexdocs.pm/plug/Plug.Conn.html#register_before_send/2)which `PlugHTTPCache` uses, which in our case is nice
- however there can be some cases when you want it. For instance, you could want to cache some cookies (fro A/B testing or whatever)

**Comment by niccolox** [comment]
> > plug now, I think this is logical problem you highlighted, I may need to adjust this more
> 
> I still think what you wanna do here is:
> 
> * to return cached page for unauthenticated user
> * to **not** return cached page for authenticated users
> 
> This is doable, but keep in mind that you should **not** return cache control headers beyond your Phoenix app if you do so, because intermediary proxies (CloudFlare...) will cache the page for everybody, unless you configure something there as well.
> 

yes, agreed, I dont want session leakage, have spent a LOT of time ensuring that doesnt happen in Varnish cache. I think I dont have session leakage in my setup; Phoenix + plug_cache/plug_cache_control + Cloudflare but will check again


> Usually, you have public, cacheable pages and private, non-cacheable ones. Please expand on your use-case because it's not clear to me and if I guessed correctly what you try to achieve, then the problem with returning cached pages to authenticated users may remain.
> 

will double/triple check and make more explicit

> Long story short you shouldn't set cache control headers that allow caching on private pages that shouldn't be cached by shared caches. If you do so you gonna have problems ☺
> 

yes, I know, session leakage is very bad

> > regarding LiveView, I think you need to put the session/cookie on the websocket stream and cache the html that is not the DOM patch ws
> > Caching private liveviews is actually what I'm trying to achieve. Some PRs remain to be merged in Phoenix & Phoenix LiveView, it's still a long way. But it would be the best of both world.
> 
> > how so? can you expand on that?
> > Yes, and gonna have to write about this:
> 
> * when using the session `Plug.Conn.put_session/3`, the `set-cookie` header is not directly set
> * instead, session data is kept in memory
> * the `set-cookie` header is set [just before](https://github.com/elixir-plug/plug/blob/b05cd27012511426d1c75834fe66566539ee89cd/lib/plug/conn.ex#L1848-L1867) the response is sent to the adapter (cowboy for instance)
> * as a consequence, one has no way of accessing the `set-cookie` header even through the[ registered callbacks ](https://hexdocs.pm/plug/Plug.Conn.html#register_before_send/2)which `PlugHTTPCache` uses, which in our case is nice
> * however there can be some cases when you want it. For instance, you could want to cache some cookies (fro A/B testing or whatever)

will do more reading, a nice entry point into LiveView lifecycle

would you be ok with the demo app fork including liveview?

**Comment by tanguilp** [comment]
> will double/triple check and make more explicit

You shall fear no more, as `http_cache` v0.3.1 is out and will raise an error (by default) when caching a cookie (`set-cookie`) in a shared cache :partying_face: 

> will do more reading, a nice entry point into LiveView lifecycle

It's actually just Phoenix. Liveview is more complex. Discussion here → https://github.com/phoenixframework/phoenix/pull/5667

> would you be ok with the demo app fork including liveview?

I was thinking of another demo app actually. I'd be glad if we could work together on it!

It depends on:
- patching Phoenix (the PR mentionned above)
- patching `phoenix_live_view` (not started yet)

My goal is to demonstrate the *public cacheable liveview with private rehydration concept` as described [here](https://elixirforum.com/t/http-caching-liveviews-first-render/59180).

The idea I have is the following: set up a demo shop app. Product pages (well, page) is composed of a few products and is cached. The flow is the following:
- an unauthenticated user visits the front page, the cached version is returned
- after intial load, sessionless Liveview updates a few things on the page (e.g. after 10s the price of one item changes)
- the user logs in
- he returns on the front page. Now not only elements are updated live (prices, # of reviews, rating etc) but the number of items in the cart (which is an information of the user = session) is shown as well. And the returned page is still the cached one!

If you're interested let me know. I'll need:
- to publish patched `phoenix` and `phoenix_live_view` on GH
- open a new project

Knowing that if eventually these changes are not merged in Phoenix, we'll have worked for nothing ☹ But hopefully this will help with advertising and adopting this pattern.

**Comment by niccolox** [comment]
> Knowing that if eventually these changes are not merged in Phoenix, we'll have worked for nothing ☹ But hopefully this will help with advertising and adopting this pattern.

perfect, great scope

even if its not core I hope we might be able to build modules (hex) that can extend core and make a solution

you ok with?
github
github cicd
github pages docs
docker compose

hosted options?
1 cluster vps on proxmox ovh 
2. cluster on fly.io
cdn cloudflare
perf 1 gtmetrix
perf 2 webpagetest

regions/metros Paris and San Francisco?

before / after optimization
again done this a lot myself commercially and so would bring that to the party

love the idea of a liveview shop (product, category, line item, cart, checkout page, stripe)

I wanted to do this again (I built one in Phoenix controllers and flat views but wanted to do it again on liveviews) 
as tools? 

I have 10 days approx this Christmas to do this, I think we can get a skeleton and maybe an alpha out the door (or at least a solid start) by end of Jan 2024?

**Comment by tanguilp** [comment]
> even if its not core I hope we might be able to build modules (hex) that can extend core and make a solution

It's gonna have to be a fork unfortunately.

> I have 10 days approx this Christmas to do this, I think we can get a skeleton and maybe an alpha out the door (or at least a solid start) by end of Jan 2024?

Yeah so I think the scope you envision is way wider that what I meant :sweat_smile: I just wanted one Liveview and a static auth page :smile: As a GH repo similar to this demo project. My goals are:
- to test the concept
- to give an example to users
- to make a video to advertise it

My time is very limited and I'll have no more than 2 days for it.

That said, it's more than welcome if you have more time and want to make a wider demo and deploy it :fire:

**Comment by niccolox** [comment]
> Yeah so I think the scope you envision is way wider that what I meant 😅 I just wanted one Liveview and a static auth page 😄 As a GH repo similar to this demo project. My goals are:
> 
> * to test the concept
> * to give an example to users
> * to make a video to advertise it
> 
> My time is very limited and I'll have no more than 2 days for it.
> 
> That said, it's more than welcome if you have more time and want to make a wider demo and deploy it 🔥

lets work together as best we can and see where we get. I have from tomorrow to Jan 1 vacation (with Christmas family obligations) and I am aligned with the goals here in your project scope and lets see where I get to on my side, I am more interested in deployment on fly and a small cluster than complex functionality right now

start the project with a markdown checklist and lets start

**Comment by tanguilp** [comment]
Here we go: https://github.com/tanguilp/cacheable_liveviews

Comments in th issues there. See ya

**Comment by niccolox** [comment]
fwiw, I ended up with this

```elixir
defmodule FolkbotWeb.Plug.DynamicCacheControl do
  @moduledoc """
  Manages the adding of cache-control headers to public requests so CDN
  can do some caching
  """
  import Plug.Conn


  def init(opts), do: opts

  def call(conn = %{assigns: %{current_user: user}}, _opts) when not is_nil(user), do: conn

  def call(conn = %{assigns: %{current_user: nil}}, [directives]) do

    opts = PlugHTTPCache.init(Application.get_env(:folkbot, :plug_http_cache_opts))
    conn = PlugHTTPCache.call(conn, opts)

    opts = PlugCacheControl.init([directives])
    conn = PlugCacheControl.call(conn, opts)

  end

end
```

**Comment by tanguilp** [comment]
I need to implement private caching with `plug_http_cache` as well. Will probably wait for first user to ask though.
